=== Grupo-IRP/XML-DTD-y-XSD/DTD Rick.dtd
<!-- Libros-->
<!ELEMENT Biblioteca (libros|revistas|periodicos)+>
<!ELEMENT libros (libro)+>
<!ELEMENT libro (titulo|indice|capitulo|sinopsis)+>
<!ATTLIST libro
        id CDATA #REQUIRED
        paginas CDATA #REQUIRED
        tipo_clase CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT capitulo (titulo|contenido)+>
<!ATTLIST capitulo
        paginas_capitulo CDATA #REQUIRED>
<!ELEMENT contenido (#PCDATA)>
<!ATTLIST contenido
        enlace CDATA #REQUIRED>
<!ELEMENT sinopsis (#PCDATA)>

<!-- Revistas-->

<!ELEMENT revistas (revista)*>
<!ELEMENT revista (titulo|numero_revista|indice_contenido|seccion)*>
<!ATTLIST revista
        id CDATA #REQUIRED
        paginas CDATA #REQUIRED
        tipo_clase CDATA #REQUIRED>
<!ELEMENT numero_revista (#PCDATA)>
<!ELEMENT indice_contenido (#PCDATA)>
<!ELEMENT seccion (titulo|contenido|titlo)*>
<!ATTLIST seccion
        paginas_seccion CDATA #REQUIRED>
<!ATTLIST contenido
        enlace CDATA #REQUIRED>
<!ELEMENT titlo (#PCDATA)>


<!-- Periodicos-->
<!ELEMENT periodicos (periodico)+>
<!ELEMENT periodico (indice|secciones|contenido)+>
<!ATTLIST periodico
        fecha_de_publicacion CDATA #REQUIRED
        id CDATA #REQUIRED>
<!ATTLIST periodico tipo_clase (nacionales | internacionales) #REQUIRED>
<!ELEMENT secciones (articulo)+>
<!ATTLIST secciones tipo_seccion (economica | opinion | deportes | nacional | internacional) #REQUIRED>
<!ELEMENT articulo (#PCDATA)>
<!ATTLIST articulo
        autor CDATA #REQUIRED>

=== Grupo-IRP/XML-DTD-y-XSD/XML Rick.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Biblioteca SYSTEM "DTD Rick.dtd">

<Biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="XSD Rick.xsd">

    <libros>

        <libro id="L0001" tipo_clase="novela" paginas="200" > 
            <titulo>Ruina y terror</titulo>
            <indice>
               Principio y fin
                 
            </indice>
            <capitulo paginas_capitulo="50">
                <titulo>El fin del mundo</titulo>
                <contenido enlace="https://es.wikipedia.org/wiki/Las_ruinas"></contenido>
            </capitulo>

           

            <sinopsis>Todo final tiene un comienzo, no para este universo paralelo donde se envejece a la inversa</sinopsis>
        </libro>

    </libros>
    <revistas>
        <revista id="R0001" tipo_clase="investigacion" paginas="25">
            <titulo>El jabalí</titulo>
            <numero_revista>1</numero_revista>
            <indice_contenido>
                Jabalí 1-15
                Podenco 16-25
            </indice_contenido>

            <seccion paginas_seccion="10">
                <titulo>Jabalí</titulo>
             <contenido enlace=""></contenido>
            </seccion>

            <seccion paginas_seccion="10">
                <titulo>Podenco</titulo>
             <contenido enlace=""></contenido>
            </seccion>

          
        </revista>

    </revistas>
   
    
    <periodicos>
        <periodico id="P0001" tipo_clase="internacionales" fecha_de_publicacion="1963-02-01">
            <indice>
                La reproducción del percebe pag 1-3.
                Safari en Afrika pag 3-6. 
                Rayo Vallecano campeón pag 6-9.
                El tomate y sus beneficios para el ciudadano pag 9-12.
                La vieja España a ojos ajenos pag 12-20.
            </indice>
            <secciones tipo_seccion="opinion">
                <articulo autor="El Cigala">
                    La reproducción del percebe
                </articulo>
            </secciones>
            <contenido enlace="">Contenido</contenido>

            <secciones tipo_seccion="economica">
                <articulo autor="Pavlo Morales">
                    La baba del caracol
                </articulo>
            </secciones>
            <contenido enlace="">Contenido</contenido> 

            <secciones tipo_seccion="deportes">
                <articulo autor="Ismael Serrin">
                    Rayo Vallecano campeón
                </articulo>
            </secciones>
            <contenido enlace="https://elpais.com/deportes/2022-05-08/alcaraz-y-zverev-de-martillo-a-martillo.html">Contenido</contenido>

            <secciones tipo_seccion="nacional">
                <articulo autor="Paco Lucia">
                   El tomate y sus beneficios para el ciudadano
                </articulo>
            </secciones>
            <contenido enlace="https://elpais.com/espana/2022-05-08/el-rastro-del-asesino-llega-a-irun.html?autoplay=1">Contenido</contenido>

            <secciones tipo_seccion="internacional">
                <articulo autor="Benito K">
                    La vieja España a ojos ajenos
                </articulo>
            </secciones>
            <contenido enlace="https://elpais.com/internacional/2022-05-08/ni-dios-sabe-por-que-nos-bombardean.html">Contenido</contenido>


        </periodico>

       
    </periodicos>

    
   
</Biblioteca>
